import { Work } from "@/types/work";
import { UserProfile } from "@/types/user";

export const mockUser: UserProfile = {
  id: "1",
  username: "lucas",
  name: "Lucas",
  bio: "Building my cultural archive.",
  created_at: new Date().toISOString(),
};

export const mockWorks: Work[] = [
  {
    id: "1",
    user_id: "1",
    title: "Blade Runner",
    subtitle: "Denis Villeneuve",
    type: "movie",
    status: "finished",
    rating: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    user_id: "1",
    title: "Duna",
    subtitle: "Frank Herbert",
    type: "book",
    status: "in_progress",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    user_id: "1",
    title: "The Last of Us",
    type: "game",
    status: "want",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
    {
    id: "4",
    user_id: "1",
    title: "The Last of Us PT 2",
    type: "game",
    status: "want",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
  id: "4",
  user_id: "1",
  title: "Interestelar",
  type: "movie",
  status: "finished",
  rating: 5,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
},
{
  id: "5",
  user_id: "1",
  title: "Clube da Luta",
  type: "movie",
  status: "finished",
  rating: 5,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
},
{
  id: "6",
  user_id: "1",
  title: "O Nome do Vento",
  type: "book",
  status: "in_progress",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
},
{
  id: "7",
  user_id: "1",
  title: "Neuromancer",
  type: "book",
  status: "want",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
},
{
  id: "8",
  user_id: "1",
  title: "Dark Souls III",
  type: "game",
  status: "finished",
  rating: 5,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
},
{
  id: "9",
  user_id: "1",
  title: "The Witcher 3",
  type: "game",
  status: "in_progress",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
},
{
  id: "10",
  user_id: "1",
  title: "Attack on Titan",
  type: "anime",
  status: "finished",
  rating: 4,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
},
{
  id: "11",
  user_id: "1",
  title: "Death Note",
  type: "anime",
  status: "finished",
  rating: 5,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
},
{
  id: "12",
  user_id: "1",
  title: "Berserk",
  type: "manga",
  status: "in_progress",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
},
{
  id: "13",
  user_id: "1",
  title: "Chainsaw Man",
  type: "manga",
  status: "want",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
},
{
  id: "14",
  user_id: "1",
  title: "Death Note",
  type: "manga",
  status: "want",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}
];